CREATE TABLE PostLikes
(
    Id        UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    CreatedAt DATETIME         NOT NULL DEFAULT GETDATE(),
    PostId    UNIQUEIDENTIFIER NOT NULL,
    UserId    UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (PostId) REFERENCES Posts (Id),
    FOREIGN KEY (UserId) REFERENCES Users (Id),
    UNIQUE (PostId, UserId)
);