CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Surname NVARCHAR(100) NOT NULL,
    Age INT NOT NULL
);

CREATE TABLE Posts (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    DeletedAt DATETIME NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);