CREATE TABLE Comments
(
    Id        UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Content   NVARCHAR(1000) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    PostId    UNIQUEIDENTIFIER NOT NULL,
    UserId    UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (PostId) REFERENCES Posts(Id),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);