// <auto-generated />
using System;
using EFP48.EFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFP48.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFP48.Data.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("my_categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("561ac3ea-6374-4b26-b422-4c619bdc26fa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = new Guid("34c0032d-9a67-40a8-b6c4-8c0d15b23650"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Computers"
                        },
                        new
                        {
                            Id = new Guid("89bd4978-0429-4913-8c74-843f24e35cb6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = new Guid("8e1b8de7-421b-4020-ac41-3e96b01ba8d3"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TV-sets"
                        },
                        new
                        {
                            Id = new Guid("4af1ce03-b37c-40a5-8462-28494820f53f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = new Guid("0d5d102d-e7b0-4a2e-a4fa-076deb014547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mice"
                        },
                        new
                        {
                            Id = new Guid("6c179026-9a44-4eca-b75a-811ebb8a577a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Keyboards"
                        });
                });

            modelBuilder.Entity("EFP48.Data.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-4aaa-8aaa-111111111111"),
                            CategoryId = new Guid("561ac3ea-6374-4b26-b422-4c619bdc26fa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "iPhone 15",
                            Price = 999.99000000000001
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-4aaa-8aaa-111111111112"),
                            CategoryId = new Guid("561ac3ea-6374-4b26-b422-4c619bdc26fa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Galaxy S24",
                            Price = 899.99000000000001
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-4aaa-8aaa-111111111113"),
                            CategoryId = new Guid("561ac3ea-6374-4b26-b422-4c619bdc26fa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Google Pixel 8",
                            Price = 799.99000000000001
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-4aaa-8aaa-111111111114"),
                            CategoryId = new Guid("561ac3ea-6374-4b26-b422-4c619bdc26fa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi 14",
                            Price = 699.99000000000001
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-4aaa-8aaa-111111111115"),
                            CategoryId = new Guid("561ac3ea-6374-4b26-b422-4c619bdc26fa"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OnePlus 12",
                            Price = 749.99000000000001
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-4bbb-8bbb-222222222221"),
                            CategoryId = new Guid("34c0032d-9a67-40a8-b6c4-8c0d15b23650"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dell OptiPlex 7010",
                            Price = 1200.0
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-4bbb-8bbb-222222222222"),
                            CategoryId = new Guid("34c0032d-9a67-40a8-b6c4-8c0d15b23650"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HP Pavilion Desktop",
                            Price = 950.0
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-4bbb-8bbb-222222222223"),
                            CategoryId = new Guid("34c0032d-9a67-40a8-b6c4-8c0d15b23650"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lenovo ThinkCentre",
                            Price = 1100.0
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-4bbb-8bbb-222222222224"),
                            CategoryId = new Guid("34c0032d-9a67-40a8-b6c4-8c0d15b23650"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "iMac 24",
                            Price = 1800.0
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-4bbb-8bbb-222222222225"),
                            CategoryId = new Guid("34c0032d-9a67-40a8-b6c4-8c0d15b23650"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Asus ExpertCenter",
                            Price = 1050.0
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-4ccc-8ccc-333333333331"),
                            CategoryId = new Guid("89bd4978-0429-4913-8c74-843f24e35cb6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MacBook Air M3",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-4ccc-8ccc-333333333332"),
                            CategoryId = new Guid("89bd4978-0429-4913-8c74-843f24e35cb6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dell XPS 15",
                            Price = 1700.0
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-4ccc-8ccc-333333333333"),
                            CategoryId = new Guid("89bd4978-0429-4913-8c74-843f24e35cb6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HP Spectre x360",
                            Price = 1600.0
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-4ccc-8ccc-333333333334"),
                            CategoryId = new Guid("89bd4978-0429-4913-8c74-843f24e35cb6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lenovo Legion 5",
                            Price = 1400.0
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-4ccc-8ccc-333333333335"),
                            CategoryId = new Guid("89bd4978-0429-4913-8c74-843f24e35cb6"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Asus ROG Zephyrus",
                            Price = 1900.0
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4ddd-8ddd-444444444441"),
                            CategoryId = new Guid("8e1b8de7-421b-4020-ac41-3e96b01ba8d3"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung QLED 55",
                            Price = 1300.0
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4ddd-8ddd-444444444442"),
                            CategoryId = new Guid("8e1b8de7-421b-4020-ac41-3e96b01ba8d3"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LG OLED C3",
                            Price = 2100.0
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4ddd-8ddd-444444444443"),
                            CategoryId = new Guid("8e1b8de7-421b-4020-ac41-3e96b01ba8d3"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sony Bravia XR",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4ddd-8ddd-444444444444"),
                            CategoryId = new Guid("8e1b8de7-421b-4020-ac41-3e96b01ba8d3"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Philips Ambilight 65",
                            Price = 1700.0
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4ddd-8ddd-444444444445"),
                            CategoryId = new Guid("8e1b8de7-421b-4020-ac41-3e96b01ba8d3"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TCL 4K UHD",
                            Price = 900.0
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-4eee-8eee-555555555551"),
                            CategoryId = new Guid("4af1ce03-b37c-40a5-8462-28494820f53f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dell UltraSharp 27",
                            Price = 600.0
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-4eee-8eee-555555555552"),
                            CategoryId = new Guid("4af1ce03-b37c-40a5-8462-28494820f53f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LG UltraGear 32",
                            Price = 750.0
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-4eee-8eee-555555555553"),
                            CategoryId = new Guid("4af1ce03-b37c-40a5-8462-28494820f53f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung Odyssey G7",
                            Price = 800.0
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-4eee-8eee-555555555554"),
                            CategoryId = new Guid("4af1ce03-b37c-40a5-8462-28494820f53f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Asus ProArt Display",
                            Price = 950.0
                        },
                        new
                        {
                            Id = new Guid("e5555555-5555-4eee-8eee-555555555555"),
                            CategoryId = new Guid("4af1ce03-b37c-40a5-8462-28494820f53f"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Acer Predator XB",
                            Price = 850.0
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-4fff-8fff-666666666661"),
                            CategoryId = new Guid("0d5d102d-e7b0-4a2e-a4fa-076deb014547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Logitech MX Master 3",
                            Price = 120.0
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-4fff-8fff-666666666662"),
                            CategoryId = new Guid("0d5d102d-e7b0-4a2e-a4fa-076deb014547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Razer DeathAdder V3",
                            Price = 99.989999999999995
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-4fff-8fff-666666666663"),
                            CategoryId = new Guid("0d5d102d-e7b0-4a2e-a4fa-076deb014547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SteelSeries Rival 5",
                            Price = 79.989999999999995
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-4fff-8fff-666666666664"),
                            CategoryId = new Guid("0d5d102d-e7b0-4a2e-a4fa-076deb014547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HyperX Pulsefire",
                            Price = 69.989999999999995
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-4fff-8fff-666666666665"),
                            CategoryId = new Guid("0d5d102d-e7b0-4a2e-a4fa-076deb014547"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Corsair Dark Core",
                            Price = 89.989999999999995
                        },
                        new
                        {
                            Id = new Guid("e7777777-7777-4aaa-8aaa-777777777771"),
                            CategoryId = new Guid("6c179026-9a44-4eca-b75a-811ebb8a577a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Logitech MX Keys",
                            Price = 130.0
                        },
                        new
                        {
                            Id = new Guid("e7777777-7777-4aaa-8aaa-777777777772"),
                            CategoryId = new Guid("6c179026-9a44-4eca-b75a-811ebb8a577a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Razer BlackWidow V4",
                            Price = 180.0
                        },
                        new
                        {
                            Id = new Guid("e7777777-7777-4aaa-8aaa-777777777773"),
                            CategoryId = new Guid("6c179026-9a44-4eca-b75a-811ebb8a577a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Corsair K95 RGB",
                            Price = 200.0
                        },
                        new
                        {
                            Id = new Guid("e7777777-7777-4aaa-8aaa-777777777774"),
                            CategoryId = new Guid("6c179026-9a44-4eca-b75a-811ebb8a577a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SteelSeries Apex Pro",
                            Price = 210.0
                        },
                        new
                        {
                            Id = new Guid("e7777777-7777-4aaa-8aaa-777777777775"),
                            CategoryId = new Guid("6c179026-9a44-4eca-b75a-811ebb8a577a"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Keychron K8",
                            Price = 110.0
                        });
                });

            modelBuilder.Entity("EFP48.Data.Entity.Product", b =>
                {
                    b.HasOne("EFP48.Data.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EFP48.Data.Entity.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
